FROM osrf/ros:noetic-desktop-full
# ARG USER=user
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /home/drone
# Install dependencies
SHELL ["/bin/bash", "-c"]
RUN apt-get update  && apt-get dist-upgrade -y && apt-get install -y \
    curl wget git cmake libgl1-mesa-glx mesa-utils python3 python3-pip \
    zstd  && \
    # nvidia-cuda-toolkit
    rm -rf /var/lib/apt/lists/*

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
RUN mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
RUN wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-ubuntu2004-11-1-local_11.1.1-455.32.00-1_amd64.deb
RUN dpkg -i cuda-repo-ubuntu2004-11-1-local_11.1.1-455.32.00-1_amd64.deb
RUN apt-key add /var/cuda-repo-ubuntu2004-11-1-local/7fa2af80.pub
RUN apt-get update
RUN apt-get -y install cuda
    
RUN export PATH=/usr/local/cuda-11.1/bin${PATH:+:${PATH}}
RUN export LD_LIBRARY_PATH=/usr/local/cuda-11.1/lib64:$LD_LIBRARY_PATH
RUN export LD_LIBRARY_PATH=/usr/local/cuda-11.1/include:$LD_LIBRARY_PATH    

# Install gazebo
RUN curl -sSL http://get.gazebosim.org | bash
RUN source /opt/ros/${ROS_DISTRO}/setup.bash

# PX4
# RUN git clone https://github.com/PX4/Firmware.git --recursive
# RUN cd /home/drone/Firmware && chmod +x /home/drone/Firmware/Tools/setup/ubuntu.sh && cd /home/drone/Firmware/Tools/setup/ && ./ubuntu.sh
# RUN cd /home/drone/Firmware && DONT_RUN=1 make px4_sitl_default gazebo-classic
# RUN source /opt/ros/noetic/setup.bash

# RUN source /home/drone/Firmware/Tools/simulation/gazebo-classic/setup_gazebo.bash /home/drone/Firmware /home/drone/Firmware/build/px4_sitl_default
# RUN export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/drone/Firmware
# RUN export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/drone/Firmware:/home/drone/Firmware/Tools/simulation/gazebo-classic/sitl_gazebo-classic
# RUN source /opt/ros/noetic/setup.bash && roslaunch px4 px4.launch

# Mavros
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt update
RUN apt-get install ros-noetic-mavros ros-noetic-mavros-extras -y
# Mavros geographic dataset
RUN wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
RUN chmod a+x install_geographiclib_datasets.sh
RUN ./install_geographiclib_datasets.sh

# Create workspace
RUN source /opt/ros/noetic/setup.bash && \ 
    mkdir -p /home/drone/catkin_ws && \
    mkdir -p /home/drone/catkin_ws/src && \
    cd /home/drone/catkin_ws && \
    # catkin_init_workspace && \
    catkin_make

# UAV
COPY ./uav_mission_planner /home/drone/catkin_ws/src

# Camera
RUN wget https://stereolabs.sfo2.cdn.digitaloceanspaces.com/zedsdk/4.1/ZED_SDK_Ubuntu20_cuda11.8_v4.1.3.zstd.run
RUN chmod +x ZED_SDK_Ubuntu20_cuda11.8_v4.1.3.zstd.run; ./ZED_SDK_Ubuntu20_cuda11.8_v4.1.3.zstd.run -- silent skip_tools skip_cuda
RUN cd /home/drone/catkin_ws/src && git clone --recursive https://github.com/stereolabs/zed-ros-wrapper.git
RUN cd /home/drone/catkin_ws && rosdep install --from-paths src --ignore-src -r -y
RUN cd /home/drone/catkin_ws && source ./devel/setup.bash && catkin_make -DCMAKE_BUILD_TYPE=Release 

RUN source /opt/ros/noetic/setup.bash && \
    cd /home/drone/catkin_ws && \
    catkin_make

RUN cd /home/drone/catkin_ws    
RUN pwd && ls -l
# RUN cd /home/drone/catkin_ws/src/uav_mission_planner && pip install -r requirements.txt
# RUN curl https://ctu-mrs.github.io/ppa-stable/add_ppa.sh | bash
# RUN apt-get update && apt-get install -y ros-noetic-mrs-uav-system-full ros-noetic-mrs-uav-gazebo-simulation ros-noetic-mrs-uav-px4-api
# RUN /bin/bash -c "roscd mrs_uav_gazebo_simulation/tmux/one_drone && ./start.sh"
RUN source /home/drone/catkin_ws/devel/setup.bash && roslaunch uav_mission_planner launch.launch